services:
    TurboLabIt\Encryptor\Encryptor:
      autowire: true
      public: true
      arguments:
        $secretKey: '%env(APP_SECRET)%'

    TurboLabIt\Encryptor\Command\EncryptCommand:
        autowire: true
        tags:
            - { name: 'console.command' }
